services:
  # PostgreSQL Database 17.5
  postgres:
    build: ./db
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - fam_network

  # PgAdmin for database management
  pgadmin:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin123}
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fam_network

  # Backend (Spring Boot) - TODO: Uncomment when backend is ready
  # backend:
  #   build: ./backend
  #   container_name: fam_backend
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB:-fam_db}
  #     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-fam_user}
  #     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-changeme}
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - fam_network

  # Frontend (Next.js) - TODO: Uncomment when frontend is ready
  # frontend:
  #   build: ./frontend
  #   container_name: fam_frontend
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:8080
  #   depends_on:
  #     - backend
  #   networks:
  #     - fam_network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  fam_network:
    driver: bridge
